### ISSUE TITLE
create rust program with the SDK to mimic infinite proof submission scripts

### ISSUE THREAD

**Issue by entropidelic** [yetanotherco/aligned_layer#1015]
PR: #1040 
Consider these two scripts, and the Make target `make batcher_send_burst_groth16`, which uses them:
* `batcher/aligned/send_burst_tasks.sh` 
* `batcher/aligned/generate_proof_and_send.sh`

Since they are written in bash, they are hard to maintain and prone to bugs when the system is updated. It would be nice to have a rust program using the Aligned SDK that mimics the functionality when we call `make batcher_send_burst_groth16`.
 
At a high level, the rust program should:
* call Go to generate a proof for a very simple Groth16 circuit which is in a Go script 
* submit the proofs with the sdk
* sleep and repeat

Some details:
* the generation and submission of the proofs should be in a separate thread, so that it can be done continuously (check line 29 in `batcher/aligned/send_burst_tasks.sh`)
* the groth16 script for the proof generation receives a `x` input, used for the proof generation. This has to be updated so that different proofs are generated each time. This lets us keep sending infinite proofs
* It should work with payable and non payable addresses

**Comment by MauroToscano** [comment]
Finished, needs a fix
