### ISSUE TITLE
(fix): Stop hardcoding aggregators IP address and port.

### ISSUE THREAD

**Issue by isoprophlex** [yetanotherco/aligned_layer#102]
In NewOperatorFromConfig function, from ./operator/pkg/operator.go, it would be good if we can avoid hardcoding IP address of the aggregator.

**Comment by jpx** [comment]
In the same vein, the Prometheus metrics port is hardcoded [there](https://github.com/yetanotherco/aligned_layer/blob/31b589041727b63a662b126d4148ca7db6460842/aggregator/internal/pkg/aggregator.go#L74C3-L74C27). I'll consider opening a separate issue, if that is not yet on the radar.
