### ISSUE TITLE
Enforce generalized ```VerificationKey``` proving system on Operators, make sure Batcher checks it too

### ISSUE THREAD

**Issue by MauroToscano** [yetanotherco/aligned_layer#1042]

**Comment by gabrielbosio** [comment]
By adding the verification key to the verification data, are we not already enforcing the verification key? Because if the verification key is different then the batch Merkle root check would fail.

**Comment by gabrielbosio** [comment]
> By adding the verification key to the verification data, are we not already enforcing the verification key? Because if the verification key is different then the batch Merkle root check would fail.

Adding the verification key to the verification data already enforces the verification key. Closing.
