### ISSUE TITLE
feat (task-sender): estimate aggregator fee

### ISSUE THREAD

**Issue by taturosati** [yetanotherco/aligned_layer#105]
Should have a better way to estimate aggregators gas cost. Maybe interpolation based on semi-fixed gas_limit * gas_price on the moment. Default value is now 1_000_000_000_000_000 (10^15). And this seems to cover gas cost when all operators sign.

Depends on https://github.com/yetanotherco/aligned_layer/pull/59

**Comment by MauroToscano** [comment]
We need to redesign the payments, I'm closing this until then
