### ISSUE TITLE
AlignedLayerServiceManager incomplete initialization

### ISSUE THREAD

**Issue by entropidelic** [yetanotherco/aligned_layer#1192]
Even though the `__ServiceManagerBase_init()` hook also initializes the contract owner, the `AlignedLayerServiceManager`
contract does not call initialize a reward initiator like in the `ServiceManagerBase` contract.

```solidity
...
contract AlignedLayerServiceManager is
...
{
    ...
    function initialize(address _initialOwner) public initializer {
        _transferOwnership(_initialOwner);
    }
    ...
}
```

```solidity
...
contract ServiceManagerBase is
...
{
    ...
    function __ServiceManagerBase_init(
        address initialOwner,
        address _rewardsInitiator
    ) internal virtual onlyInitializing {
        _transferOwnership(initialOwner);
        _setRewardsInitiator(_rewardsInitiator);
    }
    ...
}
```

## Recommendations

We recommend calling `__ServiceManagerBase_init()` during the initialization of the `BatcherPaymentService` (**Marian**: I think they meant `AlignedServiceManager` here) contract to ensure that the contract is correctly initialized.

```solidity
...
contract AlignedLayerServiceManager is
...
{
    ...
    function initialize(
        address initialOwner,
        address _rewardsInitiator
    ) public initializer {
        __ServiceManagerBase_init(initialOwner, _rewardsInitiator);
    }
    ...
}
```

**Comment by uri-99** [comment]
We already have `__ServiceManagerBase_init`, here: https://github.com/yetanotherco/aligned_layer/blob/staging/contracts/src/core/AlignedLayerServiceManager.sol#L69
