### ISSUE TITLE
fix(cli): Aligned CLI should accept Public Inputs as an optional input for Risc0

### ISSUE THREAD

**Issue by PatStiles** [yetanotherco/aligned_layer#1201]
The Aligned submit CLI currently treats the public input argument for Risc0 as a required argument even though it is optional. We should submitting Risc0 proofs with no public input.

ref:
https://github.com/yetanotherco/aligned_layer/blob/testnet/batcher/aligned/src/main.rs#L493
https://github.com/yetanotherco/aligned_layer/blob/testnet/batcher/aligned/src/main.rs#L574

**Comment by JuArce** [comment]
#1204
