### ISSUE TITLE
refactor(metrics): avoid thread sleeping for batcher restarts.

### ISSUE THREAD

**Issue by IAvecilla** [yetanotherco/aligned_layer#1259]
We currently have a `thread::sleep` when increasing the batcher restart metric [here](https://github.com/yetanotherco/aligned_layer/blob/9b0070499fbf71f354ffd474fade1a8dd1cd7c00/batcher/aligned-batcher/src/metrics.rs#L76). This was added to allow Prometheus to capture the transition from 0 to 1 during its first scrape, as otherwise, if the batcher starts before the first scrape, the variable starts at 1, and we lose visibility of this change on the dashboards.

We need to research a proper solution for this, ensuring that the variable always starts at 0 and increments only after the first scrape is done.

**Comment by JuArce** [comment]
#1236
