### ISSUE TITLE
fix: batcher queue ordering 

### ISSUE THREAD

**Issue by uri-99** [yetanotherco/aligned_layer#1400]
The batcher currently orders by max_fee . This brings errors when a user sends different max_fee for different nonces. Because of this it is currently not allowed for a user to send a bigger nonce with bigger max_fee.

The batcher should order by max_fee but and user_nonce.
So, it should order by max_fee but when a user has many nonces, order first by nonce.

This would fix many weird behaviours and constraints in the batcher queue

**Comment by MauroToscano** [comment]
As discussed this solution doesn't work, I'm closing the issue, we can re open it with a better solution later
