### ISSUE TITLE
fix: taskResponses map not being set in aligned smart contract

### ISSUE THREAD

**Issue by uri-99** [yetanotherco/aligned_layer#141]
In AlignedLayerServiceManager.sol , there is a map; 
`mapping(uint32 => bytes32) public taskResponses`

This taskResponses map is **only** being used in a require inside RespondToTask(), but never actually updated with any data;
```
require(
   taskResponses[taskResponse.taskIndex] == bytes32(0),
   "Aggregator has already responded to the task"
);
```

Meaning that we are not using this storage, and also meaning this particular `require` will always pass, even if the Task has already been responded.

It is not clear which value was meant to be stored in this map (32 bytes), but this is never done.

I believe storing 2 booleans (2 bytes, or even using first 2 bits of 1 byte) would serve its purpose: was_responded + response_value.

I think something similar to the following assignment is missing after verifying the taskResponse is appropriate:
```
taskResponses[taskResponse.taskIndex] = bytes2(true | taskResponse.proofIsCorrect)
```

Actually i think thi

**Comment by MauroToscano** [comment]
This is no longer valid
