### ISSUE TITLE
feat: upgrade to use new Eigen version

### ISSUE THREAD

**Issue by taturosati** [yetanotherco/aligned_layer#192]
Update contracts to use new eigen version that will be released soon

# Links & Guides

- core-contracts: [v0.3.0-rc0-holesky-preprod-payments](https://github.com/Layr-Labs/eigenlayer-contracts/releases/tag/v0.3.0-rc0-holesky-preprod-payments)
- middleware-contracts: [v0.2.0-rc1-holesky-preprod-payments](https://github.com/Layr-Labs/eigenlayer-middleware/releases/tag/v0.2.0-rc1-holesky-preprod-payments)
- smart contract docs: https://github.com/Layr-Labs/eigenlayer-contracts/blob/v0.3.0-rc0-holesky-preprod-payments/docs/core/PaymentCoordinator.md
- AVS ServiceManager Upgrade guide: https://hackmd.io/@Un8fEZ9aRy25eV1YL7KHZA/ry-a0w8z0#AVS-Payments-Upgrade-guide

**Comment by MauroToscano** [comment]
This shouldn't be merged until the new testnet gets upgraded
