### ISSUE TITLE
fix(merkle_verification): Fix the merkle verification ffi and add ci test

### ISSUE THREAD

**Issue by PatStiles** [yetanotherco/aligned_layer#227]
The ffi binding for lambdaworks Merkle Tree verification fails due to a change in the [Batch Commitment](https://github.com/yetanotherco/aligned_layer/blob/main/batcher/src/types/mod.rs#L73 ) types. Merkle Tree verification lacks a ci tests to catch this change. Fix the issue, add ci tests, and regenerate the merkle hash test case.

**Comment by uri-99** [comment]
Solved, merkle works and there is a test in CI
