### ISSUE TITLE
Send task waits 2 seconds instead of waiting for ETH answer

### ISSUE THREAD

**Issue by MauroToscano** [yetanotherco/aligned_layer#24]
Send task should wait for ethereum receipt

EthClient does not have  a method to wait for receipt.

EigenSDK has a method called WaitForTransactionReceipt in InstrumentedEthClient
But is needs telemetry to work

https://github.com/Layr-Labs/eigensdk-go/blob/master/chainio/clients/eth/instrumented_client.goreceipt := avsWriter.Client.WaitForTransactionReceipt(context.Background(), tx.Hash())

**Comment by taturosati** [comment]
Same issue on operator depositIntoStrategy
