### ISSUE TITLE
Adding Event Emission for Service Manager Subscription

### ISSUE THREAD

**Issue by 0xdfinity** [yetanotherco/aligned_layer#32]
### Issue Description:
The current implementation lacks a mechanism to subscribe to events from the **Service Manager**. In real-world scenarios, this subscription is crucial for handling task submissions, especially for proof verification tasks.

### Proposed Solution:
1. **Event Emission in `getMeaning()` Test Function**:
   - To address this, we recommend adding an event emission within the existing `getMeaning()` test function.
   - Emit an event when a new task (such as proof verification) is submitted to the Service Manager.
   - This event should carry relevant information about the task (e.g., task ID, type, etc.).

2. **Event Handling in the Operator**:
   - The Operator, being responsible for fetching new tasks, can listen for this emitted event.
   - Upon receiving the event, the Operator can initiate the necessary actions (e.g., fetching the task details, processing the proof, etc.).

### Benefits:
- **Real-Time Task Notification**: With this event-based approach, the Operator will be instantly notified of new tasks, improving responsiveness.
- **Modularity**: By emitting events within the Service Manager, we keep the code modular and maintain separation of concerns.

**Comment by MauroToscano** [comment]
We are re adding events. That function was for testing only, so don't worry.
