### ISSUE TITLE
Update broken link

### ISSUE THREAD

**Issue by ava-world** [yetanotherco/aligned_layer#431]
The link to operator tutorial does not show any tutorials, it displayed an error 404! Page not found

Kindly upload the tutorials, or fix the link if it's broken
![Screenshot_2024-06-17-23-29-09-742_com android chrome-edit](https://github.com/yetanotherco/aligned_layer/assets/98952181/81537b5f-fe46-4375-96c5-de88e2c663b5)

**Comment by uri-99** [comment]
solved
