### ISSUE TITLE
Document Correction

### ISSUE THREAD

**Issue by aslham** [yetanotherco/aligned_layer#434]
Please can you correct this part of your GitHub Documentation : 

Aligned Infraestructure Guide -> Aligned **Infrastructure** Guide

Update also it in Table of Contents

![image](https://github.com/yetanotherco/aligned_layer/assets/116582001/a6af681d-28bf-4c94-91a9-e3578fe76388)

![image](https://github.com/yetanotherco/aligned_layer/assets/116582001/32ec60fb-4490-408f-9a2b-b76a7817c906)

Regards,

**Comment by NicolasRampoldi** [comment]
Fixed, thanks
