### ISSUE TITLE
Error message, unable to run testnet

### ISSUE THREAD

**Issue by PrecociousAce** [yetanotherco/aligned_layer#472]
![image](https://github.com/yetanotherco/aligned_layer/assets/100510575/1c92a52f-0dba-4217-94f2-dcd1fe56c58f)
some codes are not being found and are causing an error

**Comment by MauroToscano** [comment]
We updated the requirements.Binaries require at least GLIBC 2.32. If you are using ubuntu, this would be Ubuntu 22.04 or newer for example. As an alternative you can download rust, clone the repository, and run:

```bash
make uninstall_aligned
make install_aligned_compiling
```
