### ISSUE TITLE
Add function to add funds to the batcher with a non batcher account

### ISSUE THREAD

**Issue by MauroToscano** [yetanotherco/aligned_layer#792]
Insufficient batcher balance may indefinitely block a task from being responded to. Perhaps there could be a mechanism to either top off batcher balances (currently only the batcher themselves can do it on the AlignedLayerServiceManager via receive() or createNewTask() with value), or some timeout to allow setting a new batcher for the task.

**Comment by uri-99** [comment]
Done, added `depositToBatcher(address)`
