### ISSUE TITLE
BatcherPaymentService use `Ownable2StepUpgradeable` instead of `OwnableUpgradeable`

### ISSUE THREAD

**Issue by entropidelic** [yetanotherco/aligned_layer#900]
`OwnableUpgradeable` has a shortcoming that it allows the owner to transfer ownership to a non-existent or mistyped 
address. This can lead to a loss of control over the contract. `Ownable2StepUpgradeable` is a more secure alternative.

**Reference:**
[Openzeppelin Ownable: Use Ownable2Step Instead](https://www.rareskills.io/post/openzeppelin-ownable2step)

**Comment by IAvecilla** [comment]
We are currently using the OpenZeppelin contracts from `eigenlayer-middleware`, but the contract with `Ownable2StepUpgradeable` is not yet available on the Eigenlayer side. To maintain consistency between the contract versions we are using, we should wait for them to add it before address this.
