### ISSUE TITLE
fix(aggregator): aggregator memory leak could lead to denial of service

### ISSUE THREAD

**Issue by entropidelic** [yetanotherco/aligned_layer#977]
When a new task is created, several aggregator maps are written to with task-specific information. If the service runs for long enough, it could run out of memory, causing the Aggregator to stop functioning. 

Check `aggregator/internal/pkg/aggregator.go`
These are the maps we should clean once the task is responded
```
	agg.batchesIdxByIdentifierHash[batchMerkleRoot] = batchIndex
	agg.batchCreatedBlockByIdx[batchIndex] = uint64(taskCreatedBlock)
	agg.batchesIdentifierHashByIdx[batchIndex] = batchMerkleRoot
	agg.batchDataByIdentifierHash[batchMerkleRoot] = BatchData{
		BatchMerkleRoot: batchMerkleRoot,
		SenderAddress:   [20]byte{},
	}
```

**Comment by uri-99** [comment]
solved in linked pr
