### ISSUE TITLE
fix: getLatestTaskFromEthereum should use filterer 

### ISSUE THREAD

**Issue by uri-99** [yetanotherco/aligned_layer#978]
Currently, getLatestTaskFromEthereum in `avs_subscriber.go` , parses an ABI to make a client request of a NewBatch log. It says:
```
The alternative to this is using the FilterNewBatch method from the contract's filterer, but it requires
to iterate over all the logs, which is not efficient and not needed since we only need the latest task.
```

Which is not true, since bindings filterer accepts, in `filteropts, the `fromBlock` and `toBlock` parameters.

This is why, `getLatestTaskFromEthereum` should use the bindings filterer. Using them, errors here appear on compilation and not on runtime (which was an error we had in the operators, where `NewBatch` did not exist)

**Comment by PatStiles** [comment]
ref: https://github.com/yetanotherco/aligned_layer/blob/staging/core/chainio/avs_subscriber.go#L215
